version: "3"

services:
  stencil:
    build:
      context: .
      dockerfile: Dockerfile.stencil
    image:
      dk4software/bc-stencil-theme
    ports:
      - "3000:3000"
    volumes:
      - ./src:/theme
    user: 'root'
    command: ["stencil", "start"]
  checkout-dev:
    build:
        context: .
        dockerfile: Dockerfile.checkout
    image: dk4software/bc-checkout
    volumes:
      - "./checkout-src:/checkout-src"
  checkout-server:
    image: dk4software/bc-checkout
    ports:
      - "8080:8080"
    volumes:
      - "./checkout-src:/checkout-src"
    working_dir: /checkout-src
    command: ["npm", "run", "dev:server"]