# use official node parent image
FROM node:12

# set container working directory
WORKDIR /theme

# install the cli
RUN npm -g config set user root
RUN npm install -g @bigcommerce/stencil-cli@latest

#copy theme files into container
COPY ./src ./

# install theme dependencies
RUN npm install

# default command
#ENTRYPOINT ["stencil"]
CMD ["stencil", "--help"]

# publish cli default port
EXPOSE 3000